sudo: false
language: ruby
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 2.0.0
  - jruby-9.1.9.0
before_install: gem install bundler -v 1.15.4
before_script:
  - _JAVA_OPTIONS=# See https://github.com/travis-ci/travis-ci/issues/8408
  - _JRUBY_OPTS=# See https://github.com/travis-ci/travis-ci/issues/6471
  - JRUBY_OPTS=# Not sure which is which. Don't care
